name: Build for Windows
on: 
  push:
  pull_request:
  release:
    types: # This configuration does not affect the page_build event above
      - created

jobs:
  build:
      #if: github.event_name == 'push' && contains(toJson(github.event.commits), '***NO_CI***') == false && contains(toJson(github.event.commits), '[ci skip]') == false && contains(toJson(github.event.commits), '[skip ci]') == false
      runs-on: windows-2019
      steps:
          - uses: actions/checkout@v1
            with:
                submodules: true
                  
          - name: Set triplet to only build release
            run: |
                  "`r`nset(VCPKG_BUILD_TYPE release)" | Add-Content "$env:VCPKG_INSTALLATION_ROOT\triplets\x64-windows-static.cmake"
          
          - name: Install deps with vcpkg
            run: |
                vcpkg install --triplet x64-windows-static openssl jsoncons argparse sqlite3
          
          - name: Create GCC-stealer version
            run: |
                cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET="x64-windows-static" -DCMAKE_BUILD_TYPE=Release
     
          - name: Build GCC-stealer in Release mode
            run: |
                cmake --build build --config Release

          - name: Upload binary to artifact
            uses: actions/upload-artifact@master
            with:
              name: GCC-stealer.exe
              path: build/Release/GCC-stealer.exe
                
  release:
      runs-on: ubuntu-latest
      if: github.event_name == 'release'
      needs: build
      steps:
          - name: Download GCC-stealer
            uses: actions/download-artifact@v1
            with:
                name: GCC-stealer.exe
          
          - name: Upload GCC-stealer to Github release
            uses: actions/upload-release-asset@v1
            env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
                upload_url: ${{ github.event.release.upload_url }}
                asset_path: GCC-stealer.exe/GCC-stealer.exe
                asset_name: GCC-stealer.exe
                asset_content_type: application/octet-stream
                   